### ISSUE TITLE
Mage's Water Element

### ISSUE THREAD

**Issue by Noulex** [Mortalknight/GW2_UI#101]
Just went back to frost spec on my mage and notice the UI breaks with the Water Element. Even when i get the pet buttons on the screen they are not clickable and you cant move the frame, it just resets by it self
![ApplicationFrameHost_mOlDfBMZ0i](https://user-images.githubusercontent.com/74380635/98993941-6863e580-252f-11eb-86fc-7b04fc3debe3.png)
![ApplicationFrameHost_ZzJsHA7G7o](https://user-images.githubusercontent.com/74380635/98993955-6b5ed600-252f-11eb-92b0-e6d840addd17.png)
![ApplicationFrameHost_wWKhtjwuEc](https://user-images.githubusercontent.com/74380635/98993964-6c900300-252f-11eb-8627-ed12fc9be652.png)

**Comment by Nils89** [comment]
Move it in Move HUD mode or reset it there to default position

**Comment by Noulex** [comment]
I tried that, and as soon as i press lock hud it goes back to this again. Will try it right away one more time

**Comment by Nils89** [comment]
Which version do you use?

**Comment by Noulex** [comment]
Just updated the addon and now i can move it without it resetting, but the buttons still mess up and are unclickable.

![Wow_PGDhmu4oL2](https://user-images.githubusercontent.com/74380635/98994762-9a297c00-2530-11eb-84f4-88b0753e9024.png)

**Comment by Noulex** [comment]
![Uploading Wow_GeWycGpSnM.png…]()

**Comment by Noulex** [comment]
![Wow_GeWycGpSnM](https://user-images.githubusercontent.com/74380635/98994871-ce04a180-2530-11eb-9f5c-dbeacb398cff.png)

**Comment by Noulex** [comment]
Seems like its clashing with MoveAnything, so just gonna reset that and see how it goes :) Or just delete MoveAnything ^^
