### ISSUE TITLE
Ember Court Scenario Missing Information in Objective Tracker

### ISSUE THREAD

**Issue by SSyl** [Mortalknight/GW2_UI#109]
The Venthyr/Revendreth scenario "Ember Court" has a timer and a sort of progress bar. It's not visible using the GW2 UI Objective Tracker.

Here's what it's supposed to look like in the default UI:

![image](https://user-images.githubusercontent.com/6855315/102006967-a567f700-3cea-11eb-98e0-69305870085f.png)

**Comment by Nils89** [comment]
I have no char to add that atm

**Comment by Nils89** [comment]
Added in 5.9.0
