### ISSUE TITLE
Possible typo in Setting Description for Raid Debuff Display 

### ISSUE THREAD

**Issue by cbeaulieu-gt** [Mortalknight/GW2_UI#112]
There is this string in one of the localization files:
![image](https://user-images.githubusercontent.com/8533906/108634528-22c08e00-7437-11eb-951a-f868a2071429.png)
I am not sure if this is a misspelling of the word important/imported or it has another meaning special to WoW. I did notice that the setting was referenced throughout the project with the same spelling so it might be intentional.

**Comment by Nils89** [comment]
Thanks it is fixed
