### ISSUE TITLE
[Classic] Desperate Prayer does not group ranks in spellbook 

### ISSUE THREAD

**Issue by themagicteeth** [Mortalknight/GW2_UI#113]
## Issue:
The spell ranks Desperate Prayer do not group together in the spell book as other spells do.

## Expected Behavior:
Spell should group all ranks together like the other spells do.

## Reproduction:
Have an Alliance Dwarf/Human Priest with multiple ranks of Desperate Prayer learned, open spell book.

![desperate-prayer](https://user-images.githubusercontent.com/18600239/109061380-7501e900-769b-11eb-90e4-79de209e4011.jpg)

**Comment by Nils89** [comment]
Are that all different ranks?
Can you post 2-3 spell ids?

**Comment by themagicteeth** [comment]
Yes those are all different ranks.  You can see them all here (except rank 2 since that’s the page I’m on and it is listing other ranks): https://classic.wowhead.com/spell=19236/desperate-prayer#see-also-ability

Pretty sure they are: 

13908 - Rank 1
19236 - Rank 2
19238 - Rank 3
19240 - Rank 4
19241 - Rank 5
19242 - Rank 6
19243 - Rank 7
