### ISSUE TITLE
[Classic] Target Combo Points for Druid Cat form appears on initial shapeshift without any target present

### ISSUE THREAD

**Issue by cbeaulieu-gt** [Mortalknight/GW2_UI#114]
# Issue

The combo point UI display element will appear when first shapeshifting into cat form even when having no target.

Once you select any target, whether they are hostile or friendly, the combo point display starts behaving properly and will appear and dissapear with target selection as is normally expected.

# Reproduction

![2021-03-08 07_45_25-Clipboard](https://user-images.githubusercontent.com/8533906/110337364-187bc380-7fe3-11eb-9c34-83cbb15ea51b.png)

**Comment by Nils89** [comment]
With the  option "Show Combopoints on target"?

**Comment by cbeaulieu-gt** [comment]
Yes, that option is selected. Also I updated the issue with a little more information I should have added to start with.

**Comment by Nils89** [comment]
fixed
