### ISSUE TITLE
[Classic] Debuffs on targets overlap with Druid Cat Form Combo points

### ISSUE THREAD

**Issue by cbeaulieu-gt** [Mortalknight/GW2_UI#115]
# Issue

When having an active target with debuffs the druid cat combo points overlap with the debuffs. The debuff display is not being shifted downward to allow space for the extra UI elements.

# Reproduction

![2021-03-08 07_45_54-Window](https://user-images.githubusercontent.com/8533906/110337668-6690c700-7fe3-11eb-907d-a9248f7c6552.png)

**Comment by Nils89** [comment]
fixed
