### ISSUE TITLE
[classic] action bars not switching while stealthing

### ISSUE THREAD

**Issue by robgha01** [Mortalknight/GW2_UI#116]
When i stelth on my druid the main action bar is not switching i have my regular spells this prevents me from having my stelth abilities out on the bar as i cant use it if im not in stealth.

Love the addon keep up the good work :)

**Comment by Nils89** [comment]
Maybe you have any other addon which is disabling the actionbar change? 
(Or there is a blizzard setting for that?)

We are only reskinning the default actionbars, so they have all functions which they also have in the default ui.
