### ISSUE TITLE
Cannot toggle At War with a faction on GW2 UI rep panel

### ISSUE THREAD

**Issue by Epidemedabear** [Mortalknight/GW2_UI#120]
Last night I was doing my Rogue level 50 quest, this required me to pick the pocket of a Timbermaw Shaman in Azshara, as I have already started questing in Felwood I am no longer hostile with the Timbermaw, so to be able to pickpocket them I need to set myself At War via the toggle on the reputation bar for them, cannot currently do this when using GW2 UI character panel, I can see other factions that I am At War with and they display the toggle icon, however any faction I'm not currently at war with doesn't give me the option to toggle it.

In the screenshot you can see the At War flag for the Syndicate, crossed swords icon, when using the default character panel, viewing reputations would show a tick box where that flag is allowing you to mark yourself at war wit ha specific faction if wanted.

I had to temporarily switch back to the default character panel to complete this quest.

This is using the latest TBC version of your addon

![Screenshot 2021-05-31 113809](https://user-images.githubusercontent.com/60220665/120181351-d68aa400-c204-11eb-8a21-6b9f9a322fb7.png)

**Comment by Nils89** [comment]
You can click the at war icon to toggle that option on and off. 

Can you make a screen of the default zu from the fraction Timbermaw?

**Comment by Epidemedabear** [comment]
![Screenshot 2021-05-31 141140](https://user-images.githubusercontent.com/60220665/120198655-448d9600-c21a-11eb-93db-a937ed4713a5.png)

**Comment by Nils89** [comment]
Which version do you use? 
I can mark them Ar war mit the crossing swords icon

**Comment by Epidemedabear** [comment]
1.7.1-TBC from Curse
