### ISSUE TITLE
Chat Frames Reset Upon Logout/Reload

### ISSUE THREAD

**Issue by lona808** [Mortalknight/GW2_UI#121]
Every time I log out or reload the chat frames reset positions. I have a second chat window undocked for loot/trade/LFG channels and have to reset it's position to where I want it every time the UI gets loaded - it starts off behind the minimap and therefore is halfway blocked and unreadable. It's starting to really annoy me after dealing with it for a few weeks :P

**Comment by Nils89** [comment]
We are only set the chat position during installation.  

You need to lock the frame again after you move the window, to save the position.
