### ISSUE TITLE
Weird textures when I click on a bag in the inventory

### ISSUE THREAD

**Issue by adamk33n3r** [Mortalknight/GW2_UI#124]
Whenever I click on one of the bags on the left side of the inventory window these blown up textures cover my screen. I'm not sure what the intended behavior of clicking a bag is, but I'm sure it's not this 😅

![image](https://user-images.githubusercontent.com/1350444/124006385-2f865d00-d9a8-11eb-8575-a44da1469d5a.png)

**Comment by Nils89** [comment]
Fixed
