### ISSUE TITLE
[classic] error on only one character

### ISSUE THREAD

**Issue by kylaeh** [Mortalknight/GW2_UI#125]
Here is the error log, only happens on one character and not the rest:

[string "@Interface\FrameXML\UIParent.lua"]:401: in function `MacroFrame_LoadUI'
[string "GW2_UI\immersive\skins\macro-Macro.lua"]:6: in function `SkinMacroOptions'
[string "GW2_UI\GW2_ui-1.14.2-TBC.lua"]:428: in function <GW2_UI\GW2_ui.lua:354>
[string "GW2_UI\GW2_ui-1.14.2-TBC.lua"]:663: in function <GW2_UI\GW2_ui.lua:659>
[448671.4] [ERROR]: "...terface\AddOns\Blizzard_MacroUI\Blizzard_MacroUI.lua:97: attempt to index local 'macroIcon' (a nil value)"
[string "Blizzard_MacroUI\Blizzard_MacroUI.lua"]:97: in function `MacroFrame_Update'
[string "Blizzard_MacroUI\Blizzard_MacroUI.lua"]:33: in function <...terface\AddOns\Blizzard_MacroUI\Blizzard_MacroUI.lua:32>
[string "=[C]"]: in function `Show'
[string "@Interface\FrameXML\UIParent.lua"]:2100: in function `SetUIPanel'
[string "@Interface\FrameXML\UIParent.lua"]:1945: in function `ShowUIPanel'
[string "@Interface\FrameXML\UIParent.lua"]:1806: in function <Interface\FrameXML\UIParent.lua:1802>
[string "=[C]"]: in function `SetAttribute'
[string "@Interface\FrameXML\UIParent.lua"]:2571: in function `ShowUIPanel'
[string "GW2_UI\immersive\skins\macro-Macro.lua"]:113: in function `SkinMacroOptions'
[string "GW2_UI\GW2_ui-1.14.2-TBC.lua"]:428: in function <GW2_UI\GW2_ui.lua:354>
[string "GW2_UI\GW2_ui-1.14.2-TBC.lua"]:663: in function <GW2_UI\GW2_ui.lua:659>
[448671.4] [ERROR]: "...terface\AddOns\Blizzard_MacroUI\Blizzard_MacroUI.lua:426: attempt to index local 'macroPopupIcon' (a nil value)"
[string "Blizzard_MacroUI\Blizzard_MacroUI.lua"]:426: in function `MacroPopupFrame_Update'
[string "Blizzard_MacroUI\Blizzard_MacroUI.lua"]:288: in function <...terface\AddOns\Blizzard_MacroUI\Blizzard_MacroUI.lua:282>
[string "=[C]"]: in function `Show'
[string "GW2_UI\immersive\skins\macro-Macro.lua"]:116: in function `SkinMacroOptions'
[string "GW2_UI\GW2_ui-1.14.2-TBC.lua"]:428: in function <GW2_UI\GW2_ui.lua:354>
[string "GW2_UI\GW2_ui-1.14.2-TBC.lua"]:663: in function <GW2_UI\GW2_ui.lua:659>
[448671.4] [ERROR]: "GW2_UI\inventory/bag.lua:255: attempt to call global 'mod' (a number value)"
[string "GW2_UI\inventory/bag.lua"]:255: in function <GW2_UI\inventory/bag.lua:247>
[string "GW2_UI\inventory/bag.lua"]:988: in function `LoadBag'
[string "GW2_UI\inventory/inventory.lua"]:666: in function `LoadInventory'
[string "GW2_UI\GW2_ui-1.14.2-TBC.lua"]:517: in function <GW2_UI\GW2_ui.lua:354>
[string "GW2_UI\GW2_ui-1.14.2-TBC.lua"]:663: in function <GW2_UI\GW2_ui.lua:659>

**Comment by Nils89** [comment]
Could be a conflict with any other addon. Can you disable all other addons?

**Comment by kylaeh** [comment]
process of elimination shows it to be a problem with extended character stats; disabled the addon and everything looks fine now

**Comment by Nils89** [comment]
Correct, the latest update from ECS Hand an issues which breaks the addon.
