### ISSUE TITLE
questie conflict

### ISSUE THREAD

**Issue by rpillala** [Mortalknight/GW2_UI#126]
GW2 UI told me to make a new ticket for this, so I'm sorry if it's a duplicate:

~ GW2 UI ~ Version: 1.14.2-TBC TBC Classic ~ Date: Sat Jul  3 15:34:45 2021 ~ Locale: enUS  ~
[1054285.3] [ERROR]: "Questie\Database\QuestieDB.lua:582: attempt to call field 'QueryQuest' (a table value)"
[string "=[C]"]: in function `QueryQuest'
[string "Questie\Database\QuestieDB.lua"]:582: in function `GetQuest'
[string "GW2_UI\objectives/objectives.lua"]:729: in function <GW2_UI\objectives/objectives.lua:727>
[string "GW2_UI\objectives/objectives.lua"]:879: in function <GW2_UI\objectives/objectives.lua:858>
[string "GW2_UI\objectives/objectives.lua"]:967: in function <GW2_UI\objectives/objectives.lua:966>
[string "=[C]"]: in function `SetSuperTrackedQuestID'
[string "WoWPro\WoWPro_CompatUtil.lua"]:177: in function `SuperTrack_SetSuperTrackedQuestID'
[string "WoWPro\WoWPro_Mapping.lua"]:549: in function `MapPoint'
[string "WoWPro\WoWPro_Events.lua"]:380: in function `AutoCompleteQuestUpdate'
[string "WoWPro\WoWPro_Parser.lua"]:1103: in function <WoWPro\WoWPro_Parser.lua:1068>
[string "=[C]"]: ?
[string "Questie\Libs\AceBucket-3.0\AceBucket-3.0.lua"]:73: in function <...\AddOns\Questie\Libs\AceBucket-3.0\AceBucket-3.0.lua:71>
[string "Questie\Libs\AceBucket-3.0\AceBucket-3.0.lua"]:89: in function `func'
[string "Questie\Libs\AceTimer-3.0\AceTimer-3.0.lua"]:57: in function <...ce\AddOns\Questie\Libs\AceTimer-3.0\AceTimer-3.0.lua:50>

**Comment by Nils89** [comment]
Fixed in 1.14.3
