### ISSUE TITLE
TBC - Health globe filling bug

### ISSUE THREAD

**Issue by prof-chene** [Mortalknight/GW2_UI#128]
![image_2021-07-28_194625](https://user-images.githubusercontent.com/18491300/127371215-1bd7418a-1df8-426b-8ae4-641e80d7dfef.png)

This happens quite often on the TBC version, but only on my rogue.
Sometimes the bug "stacks" and the globe is less and less filled while I'm at 100% hp, even going as far as having an empty globe.
Doing a reload UI fixes the problem.

It's the only char I PvP with, so it might be related.
Maybe the Cheat death talent or the battleground 30s rez is causing it, I didn't find the exact condition for it to happen.

**Comment by Nils89** [comment]
Strange. Hard to reproduce. Maybe any shield value is causing that

**Comment by prof-chene** [comment]
I don't get the bug when I'm shielding with my frost mage, so it might be the priest's shield they put on me ?

**Comment by Nils89** [comment]
And try it with the new version.

**Comment by Nils89** [comment]
Is it working better?

**Comment by prof-chene** [comment]
Hi @Nils89.
I tried with 1.15.1-TBC version, it is still bugged.
I can confirmed that it's due to the "Cheat death" rogue talent, as it happens while have no shield up on me.
I saw the bug stacking everytime I died during an Eye of the storm BG.

**Comment by prof-chene** [comment]
Maybe the resilience calculation for reduced damage is messed up and it ends up corrupting the globe total value or something ?

**Comment by Nils89** [comment]
should be fixed with 1.15.2-TBC
