### ISSUE TITLE
Error with new patch today on TBC client

### ISSUE THREAD

**Issue by austinmgray210** [Mortalknight/GW2_UI#130]
Version: 1.15.2-TBC TBC Classic Date: 08/31/21 16:56:54 Locale: enUS Build 2.5.2 39926
[16:54:40] [ERROR]: "GW2_UI\mainbar/micromenu.lua:386: attempt to index global 'WorldMapMicroButton' (a nil value)"
[string "TradeSkillMaster\LibTSM\Service\ErrorHandler.lua"]:761: in function <...Ons\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:717>
[string "=[C]"]: ?
[string "GW2_UI\mainbar/micromenu.lua"]:386: in function <GW2_UI\mainbar/micromenu.lua:263>
[string "GW2_UI\mainbar/micromenu.lua"]:524: in function `LoadMicroMenu'
[string "GW2_UI\GW2_ui.lua"]:614: in function <GW2_UI\GW2_ui.lua:354>
[string "GW2_UI\GW2_ui.lua"]:663: in function <GW2_UI\GW2_ui.lua:659>

**Comment by Nils89** [comment]
Temp fix:

Open that file: Gw2_UI/gw2_ui.lua
Remove „GW.LoadMicroMenu()“ in line 614

Will be fixed when the Servers are patch in EU.

**Comment by Nils89** [comment]
fixed with 1.16.0
