### ISSUE TITLE
Error displaying minimap buttons

### ISSUE THREAD

**Issue by bigdatanut** [Mortalknight/GW2_UI#131]
Version: 1.17.0-TBC TBC Classic Date: 09/04/21 21:04:15 Locale: deDE Build 2.5.2 40045
[21:03:11] [ERROR]: "...nterface\AddOns\GW2_UI\objectives/minimapButtons.lua:149: Action[SetPoint] failed because[Cannot anchor to itself]: attempted from: GwMiniMapTrackingFrame:SetPoint."
[string "=[C]"]: in function `SetPoint'
[string "GW2_UI\objectives/minimapButtons.lua"]:149: in function <...nterface\AddOns\GW2_UI\objectives/minimapButtons.lua:140>
[string "GW2_UI\objectives/minimapButtons.lua"]:184: in function <...nterface\AddOns\GW2_UI\objectives/minimapButtons.lua:170>
[string "GW2_UI\objectives/minimapButtons.lua"]:210: in function <...nterface\AddOns\GW2_UI\objectives/minimapButtons.lua:210>
[string "@Interface\SharedXML\C_TimerAugment.lua"]:16: in function <Interface\SharedXML\C_TimerAugment.lua:14>

Let me know when I can provide more information.

**Comment by Nils89** [comment]
fixed in 1.17.1-TBC
