### ISSUE TITLE
This error page pops up when open Character Sheet. Up to Date GW2UI enabled.

### ISSUE THREAD

**Issue by Fedaygin** [Mortalknight/GW2_UI#132]
Time: Thu Sep 30 23:14:58 2021
Count: 1
Stack: Interface\AddOns\GW2_UI\character/advanced_stats.lua:606: Usage: GetSpellCritChance(school)
[string "=[C]"]: ?
[string "=[C]"]: in function `GetSpellCritChance'
[string "@Interface\AddOns\GW2_UI\character/advanced_stats.lua"]:606: in function <Interface\AddOns\GW2_UI\character/advanced_stats.lua:602>
[string "@Interface\AddOns\GW2_UI\character/advanced_stats.lua"]:694: in function `showAdvancedChatStats'
[string "@Interface\AddOns\GW2_UI\character/character.lua"]:1072: in function <Interface\AddOns\GW2_UI\character/character.lua:1071>
Locals: 
/

Golden Classic_Era ver. 1.14.0.40347 in use & GW2UI 2.0.0 at the time of pop up. Let me know if require more info like screenie from character sheet or some log file. Good October o/

**Comment by Nils89** [comment]
fixed in 2.0.1
