### ISSUE TITLE
This Error Pop up came after undocked that pesky annoyance called 'Combat Log Tab'.

### ISSUE THREAD

**Issue by Fedaygin** [Mortalknight/GW2_UI#133]
Message: Interface\AddOns\GW2_UI\immersive/chatframe.lua:584: attempt to call method 'SetBackdrop' (a nil value)
Time: Thu Sep 30 23:17:34 2021
Count: 1
Stack: Interface\AddOns\GW2_UI\immersive/chatframe.lua:584: attempt to call method 'SetBackdrop' (a nil value)
[string "=[C]"]: in function `SetBackdrop'
[string "@Interface\AddOns\GW2_UI\immersive/chatframe.lua"]:584: in function <Interface\AddOns\GW2_UI\immersive/chatframe.lua:578>
[string "=[C]"]: in function `FCF_MinimizeFrame'
[string "*:OnClick"]:2: in function <[string "*:OnClick"]:1>
Locals: 
/

I minimized it & moved to bottom where can't see it cause don't want to. Shame that small handy addon called 'combat log remover' won't remove this 110% anymore or at least not with GW2UI addon. There's also chat command that can use for removal, but atm. can't recall it. Gonna take a look if can find it tomorrow. Only addons active at time of error pop up were GW2UI, Leatrix Maps & Leatrix Plus. All are up to date. Good October o/

**Comment by Nils89** [comment]
fixed in 2.0.1
