### ISSUE TITLE
tbc gw2 crash

### ISSUE THREAD

**Issue by Sepheres1989** [Mortalknight/GW2_UI#143]
Version: 1.18.0-TBC Classic Date: 03/23/22 09:43:55 Locale: deDE Build 2.5.4 42869
[09:38:47] [ERROR]: "...rface\AddOns\GW2_UI\immersive\skins\addonManager.lua:54: hooksecurefunc(): TriStateCheckbox_SetState is not a function"
[string "=[C]"]: ?
[string "=[C]"]: in function `hooksecurefunc'
[string "GW2_UI\immersive\skins\addonManager.lua"]:54: in function `SkinAddonList'
[string "GW2_UI\GW2_ui.lua"]:421: in function <GW2_UI\GW2_ui.lua:353>
[string "GW2_UI\GW2_ui.lua"]:649: in function <GW2_UI\GW2_ui.lua:645>

**Comment by Nils89** [comment]
fixed with 1.19.0-TBC

**Comment by Sepheres1989** [comment]
Hi, What does that mean? BrHolen Sie sich Outlook für AndroidVon: Glow ***@***.***>Gesendet: Mittwoch, 23. März 2022, 09:55An: Mortalknight/GW2_UI ***@***.***>Cc: Sepheres1989 ***@***.***>; Author ***@***.***>Betreff: Re: [Mortalknight/GW2_UI] tbc gw2 crash (Issue #143)
fixed with 1.19.0-TBC
