### ISSUE TITLE
Add option for all bars

### ISSUE THREAD

**Issue by YetAnotherDevWannabe** [Mortalknight/GW2_UI#148]
I really love the UI, but the fact that it allows a maximum of 5 bars of the 10 total bars is making it hard to use.
Would it be possible to have an option to have at least 2 more bars on the left side of the screen ?

**Comment by Nils89** [comment]
We only support the 5 blizzard bars

**Comment by YetAnotherDevWannabe** [comment]
:'(
Understandable, sad for me but I get it.
thx anyway

**Comment by Nils89** [comment]
But you can use bartender for example :)

**Comment by YetAnotherDevWannabe** [comment]
Yeah but it looks like s**t compared to your implementation :)
Also debuffs seems tired to some of the bars
