### ISSUE TITLE
issue: 'too many' toasts

### ISSUE THREAD

**Issue by ghost** [Mortalknight/GW2_UI#150]
Hey, great addon, I'm in love :o)

Every time I zone, reload UI or switch specs I am getting spammed with toasts informing me about "new" skills etc. (e.g. Hearth Kindeystone, unread mail, etc.).

Is there something I can do about it? Did not find anything related in the settings.

[<a href="https://ibb.co/L8tCC0v"><img src="https://i.ibb.co/XbszzWV/ghghgh.png" alt="ghghgh" border="0"></a>](url)

**Comment by Nils89** [comment]
One question: Are you have really unread mails?

**Comment by Nils89** [comment]
I try to reproduce the new skill on spec change thing, but it is not happening for me.

The new mail this is correct, that has the reason that blizzard is pushing that event on every zone change and reload.

But for spec changes that should not be the case because we filtering for that.

**Comment by Nils89** [comment]
ok, any easy way how I can reproduce this?

**Comment by Nils89** [comment]
I try this with the Kyrianer

**Comment by Nils89** [comment]
I can not reproduce that, but you can disable the New Spell alert at the settings.

If there is a unheard spell this is correct, in that case blizzard is pushing the event for that and we produce that

you ca try this:

/etrace

change the spec and post the event which pushed here

**Comment by Nils89** [comment]
have added a possible cach for that in the next update

**Comment by Nils89** [comment]
5.30.0 was release this morning, try it out
