### ISSUE TITLE
Action Bars not Saving

### ISSUE THREAD

**Issue by DreamsUnderStars** [Mortalknight/GW2_UI#154]
I have this issue: if/when I make a new character and have to load the profile I made, I have to got into the gw2 settings and turn on the bottom right and left bars and right bar. They should be saving as activated when I save/reload the mod, but they don't.

**Comment by Nils89** [comment]
True, that is because that are blizzard settings we only trigger. So atm this setting only mirrors the blizzard settings and won't save to the profile.
