### ISSUE TITLE
attempt to perform arithmetic on a string value

### ISSUE THREAD

**Issue by chaoticpriest** [Mortalknight/GW2_UI#156]
Getting error after I changed my spell queue using commands
/console SpellQueueWindow #
/dump GetCVar("SpellQueueWindow")
and changing from 32 to 27.

Afterwards, no amount of reloading or quitting the game fixes the issue. Have to turn off Cast Bars module to remove issue.

.

Message: Interface\AddOns\GW2_UI\mainbar/castingbar.lua:243: attempt to perform arithmetic on a string value
Time: Tue Aug  2 18:03:55 2022
Count: 444
Stack: Interface\AddOns\GW2_UI\mainbar/castingbar.lua:243: attempt to perform arithmetic on a string value
[string "=[C]"]: ?
[string "@Interface\AddOns\GW2_UI\mainbar/castingbar.lua"]:243: in function `method'
[string "@Interface\AddOns\GW2_UI\GW2_ui.lua"]:301: in function <Interface\AddOns\GW2_UI\GW2_ui.lua:272>

Locals: 

\
End

**Comment by Nils89** [comment]
you can disable the option for the spllQueueWindow at GW2 HUD setting for now
