### ISSUE TITLE
LoadMinimap error on load

### ISSUE THREAD

**Issue by ktgibson** [Mortalknight/GW2_UI#159]
On version 1.22.0-TBC all other addons turned off

Message: Interface\AddOns\GW2_UI\objectives/map.lua:318: hooksecurefunc(): BattlefieldFrame_OnUpdate is not a function
Time: Thu Sep  1 14:12:42 2022
Count: 1
Stack: Interface\AddOns\GW2_UI\objectives/map.lua:318: hooksecurefunc(): BattlefieldFrame_OnUpdate is not a function
[string "=[C]"]: ?
[string "=[C]"]: in function `hooksecurefunc'
[string "@Interface\AddOns\GW2_UI\objectives/map.lua"]:318: in function `LoadMinimap'
[string "@Interface\AddOns\GW2_UI\GW2_ui.lua"]:488: in function <Interface\AddOns\GW2_UI\GW2_ui.lua:361>
[string "@Interface\AddOns\GW2_UI\GW2_ui.lua"]:662: in function <Interface\AddOns\GW2_UI\GW2_ui.lua:658>

**Comment by Nils89** [comment]
You need to install the 1.0.3 Wotlk version. The tbc version is not working with wotlk

**Comment by ktgibson** [comment]
Apologies! I was using wowup so i didn't see there was a wotlk version!
