### ISSUE TITLE
Micromenu error

### ISSUE THREAD

**Issue by Praedator** [Mortalknight/GW2_UI#162]
Version: 1.0.6-Wrath Classic Date: 09/10/22 16:14:29 Locale: enUS Build 3.4.0 45506
[16:14:05] [ERROR]: "GW2_UI\mainbar\micromenu.lua:444: attempt to index global 'MainMenuBarDownload' (a nil value)"
[string "GW2_UI\mainbar\micromenu.lua"]:444: in function <GW2_UI\mainbar\micromenu.lua:282>
[string "GW2_UI\mainbar\micromenu.lua"]:575: in function `LoadMicroMenu'
[string "GW2_UI\GW2_ui.lua"]:627: in function <GW2_UI\GW2_ui.lua:361>
[string "GW2_UI\GW2_ui.lua"]:662: in function <GW2_UI\GW2_ui.lua:658>

**Comment by Nils89** [comment]
update to 1.0.7

**Comment by Praedator** [comment]
nice, thanks :)
