### ISSUE TITLE
WotLK Classic: Spellbook broken for Arcane Mage

### ISSUE THREAD

**Issue by hyperactivated** [Mortalknight/GW2_UI#163]
Logging into Mage with [Arcane Specialization](http://tbc.wowhead.com/talent-calc/mage/235005030100300150323102305020-0000000000000000000000000000-0232030002000000000000000000-) receive following error and Fire and Frost tabs of spellbook are labelled "Unknown" and have no spells in them and Teleport: Thunder Bluff and Teleport: Undercity are missing from Arcane tab.

Version: 1.0.7-Wrath Classic Date: 09/12/22 19:41:04 Locale: enUS Build 3.4.0 45506
[19:38:26] [ERROR]: "GW2_UI\character\spellbook-Spellbook.lua:137: attempt to index local 'btn' (a nil value)"
[string "GW2_UI\character\spellbook-Spellbook.lua"]:137: in function <GW2_UI\character\spellbook.lua:133>
[string "GW2_UI\character\spellbook-Spellbook.lua"]:674: in function <GW2_UI\character\spellbook.lua:619>
[19:38:56] [ERROR]: "GW2_UI\character\spellbook-Spellbook.lua:137: attempt to index local 'btn' (a nil value)"
[string "GW2_UI\character\spellbook-Spellbook.lua"]:137: in function <GW2_UI\character\spellbook.lua:133>
[string "GW2_UI\character\spellbook-Spellbook.lua"]:674: in function <GW2_UI\character\spellbook.lua:619>

**Comment by Nils89** [comment]
fixed in 1.0.8
