### ISSUE TITLE
Small quick wins/improvements 

### ISSUE THREAD

**Issue by ProgrammingSam** [Mortalknight/GW2_UI#164]
Hi there, 

First of all, thank you for you amazing job ! 

I have three small improvements/quick wins to ask for : 

- Such as the auto sell of grey stuff, I would be nice to have an auto repair to avoid a side add-on (like Broker) ; 
- Related to the previous one, a display of the 'durability cost' should be nice in the main bag in the money list on mouse over; 
- On the character display, it would be nice to see on mouse over the pvp-ilvl (mean of the related pvp stuff upgrade in battle ground). 

I don't think it should take long to develop but would be very appreciate by many of us I think 😄 

Thank in advance and have a nice day !

**Comment by Nils89** [comment]
Hi,

quick reply on the requests:
1. We already have an AutoRepair option: Gw2 Settings -> HUD -> Auto Repair (at the bottom)
2. Wil be added in the next update: But on the Hero panel and there at the durability icon
3. already in dev version

**Comment by ProgrammingSam** [comment]
Amazing ! 

Thank you for the quick update 😄

**Comment by Nils89** [comment]
<img width="494" alt="Bildschirm­foto 2022-09-12 um 18 13 54" src="https://user-images.githubusercontent.com/23194902/189704387-3f8591b2-6ea9-4eff-9595-514836a03693.png">
<img width="344" alt="Bildschirm­foto 2022-09-12 um 18 14 01" src="https://user-images.githubusercontent.com/23194902/189704401-5777b229-97ba-40b0-b083-bdefb76fea6c.png">
<img width="722" alt="Bildschirm­foto 2022-09-12 um 18 14 11" src="https://user-images.githubusercontent.com/23194902/189704406-cbde6705-37c0-47b6-b68b-ac1b1c76abe5.png">

**Comment by Nils89** [comment]
added in 6.0.0
