### ISSUE TITLE
Broken = Clean Up Bag + Hunter Arrows 

### ISSUE THREAD

**Issue by grand-lotus-iroh** [Mortalknight/GW2_UI#169]
When clicking Clean Up Bags... if you have [Saronite Razorheads arrows](https://www.wowhead.com/wotlk/item=41165/saronite-razorheads) they do not stay in container quiver. Instead they are sorted OUTSIDE of the quiver and take up space.

![image](https://user-images.githubusercontent.com/1291364/195227000-0924fa4e-3451-4c72-91fc-32239a0d1aa5.png)

**Comment by Nils89** [comment]
should be fixes in latest update
