### ISSUE TITLE
Pet Bar Doesn't Load Abilities Sometimes or Allow Toggeling of Auto Cast

### ISSUE THREAD

**Issue by Milzstream** [Mortalknight/GW2_UI#171]
I've noticed when summoning my felguard occasionally the abilities don't show up. After a reload the abilities load in but I am unable to toggle abilities, for example I can't turn off it's anguish (taunt) ability without disabling GW2_UI and toggling it.

I noticed this happening after the latest update on Wrath Classic.

**Comment by Nils89** [comment]
which version do you use?

**Comment by Milzstream** [comment]
I was using version 1.6.4-Wrath, however after updating to 1.6.5 my issue appears to have been resolved. It's possible maybe my add-on cache or something was bugged, unless something specifically targeting it in the update to 1.6.5 but the patch notes don't show anything targeting it.

**Comment by Nils89** [comment]
1.6.5 also address that issue, good to hear that it has been fixed :)

**Comment by Milzstream** [comment]
Thank you! Like others have said I appreciate all the work and time you have put into this addon, I absolutely love it!!

On Oct 14, 2022, at 3:32 AM, Glow ***@***.***> wrote:

﻿

1.6.5 also address that issue, good to hear that it has been fixed :)
