### ISSUE TITLE
GW2_UI has been blocked by an action only available to the Blizzard UI

### ISSUE THREAD

**Issue by lagrianitis** [Mortalknight/GW2_UI#174]
The following error pop ups when I interacted with the GW2 UI. This happens radomely on several action.

Eaxamples: 
   - using an item from the inventory, click mouse clicking it
   - using an ability from the action bar
   - using a macro from the action bar

```
GW2_UI has been blocked by an action only available to the Blizzard UI.
You can disable this addon and reload the UI.
```

If I reload the ui, `/reload`, I temporary am able to perform the same action. After a while it pops up again.

I use only the GW2 add on
I have tried to delete the save variables

I am running the `6.0.0-beta-3` release. I have tried the older releases, without luck.

Is there a way to debug further what exactly is causing the error ? I receive no lua errors, just a pop up window

**Comment by Nils89** [comment]
You have somehow tainted the Blizzard UI, atm that can happens by only open the Edit Mode or every much other action. Must of the are because of many errors with the blizzard interface and are out of our control

**Comment by lagrianitis** [comment]
should i remove all the WTF folder and try again, avoiding to go in Edit mode ?
