### ISSUE TITLE
Backpack Top Row Missing

### ISSUE THREAD

**Issue by KnowsJack** [Mortalknight/GW2_UI#175]
The first four slots (0-3 I believe) of the Backpack bag are missing from the UI. 

The "lock" slots icons (tooltip "Increase Backpack Size", shown to those of us who do NOT use 2-factor auth) are showing, however. Note, those "lock" icons are disabled as well.

So the total count of Backpack slots shown is 16, but if we include the "lock" slots we should see 20.

edit: on 6 beta 8.

**Comment by graldur** [comment]
I have a similar problem with the first 28 slots in the bank are blank, although items are there and a tooltip will pop up when I mouse over the items.

**Comment by Nils89** [comment]
Please try 6.8.2
