### ISSUE TITLE
request: add keybinding in options for Boss Button

### ISSUE THREAD

**Issue by grand-lotus-iroh** [Mortalknight/GW2_UI#180]
When I type `/gw2 mh` there is a Boss Button frame. May you please make it so I can add a keybind in options to auto press that button for me?

![image](https://user-images.githubusercontent.com/1291364/205739541-58a3a80a-c5e5-4de6-86c3-ea0f1ee50bab.png)

Maybe you can add it at the very bottom?

![image](https://user-images.githubusercontent.com/1291364/205739626-8bdf1b4e-84f4-4273-992b-e3f562a7d1c9.png)

**Comment by Nils89** [comment]
Thats a normal action buttons which are in the Blizzard Keybind options

**Comment by grand-lotus-iroh** [comment]
> Thats a normal action buttons which are in the Blizzard Keybind options

You are correct. Thanks for sharing!

`Extra Action Button 1`

![image](https://user-images.githubusercontent.com/1291364/205769291-b6e1d26f-7a5e-4d01-91f2-c722fad01b7f.png)
