### ISSUE TITLE
Hunter Pet Utility & Call Pet error

### ISSUE THREAD

**Issue by CLKRUN** [Mortalknight/GW2_UI#185]
50x FrameXML/SpellFlyout.lua:240: attempt to call method 'GetSpellFlyoutDirection' (a nil value)
[string "@FrameXML/SpellFlyout.lua"]:240: in function `Toggle'
[string "@FrameXML/SecureTemplates.lua"]:361: in function `handler'
[string "@FrameXML/SecureTemplates.lua"]:690: in function <FrameXML/SecureTemplates.lua:672>
[string "@FrameXML/SecureTemplates.lua"]:704: in function <FrameXML/SecureTemplates.lua:697>
[string "@FrameXML/SecureTemplates.lua"]:746: in function `SecureActionButton_OnClick'
[string "@FrameXML/ActionButton.lua"]:1175: in function <FrameXML/ActionButton.lua:1145>
[string "=[C]"]: ?

Locals:
self = SpellFlyout {
 0 = <userdata>
 isActionBar = true
 MarkDirty = <function> defined @SharedXML/LayoutFrame.lua:90
 eventsRegistered = false
 MarkClean = <function> defined @SharedXML/LayoutFrame.lua:105
 OnCleaned = <function> defined @SharedXML/LayoutFrame.lua:114
 Toggle = <function> defined @FrameXML/SpellFlyout.lua:206
 GetLayoutChildren = <function> defined @SharedXML/LayoutFrame.lua:64
 OnUpdate = <function> defined @SharedXML/LayoutFrame.lua:84
 GetAdditionalRegions = <function> defined @SharedXML/LayoutFrame.lua:76
 IsDirty = <function> defined @SharedXML/LayoutFrame.lua:110
 SetBorderSize = <function> defined @FrameXML/SpellFlyout.lua:442
 Layout = <function> defined @SharedXML/LayoutFrame.lua:333
 SetBorderColor = <function> defined @FrameXML/SpellFlyout.lua:435
 IsLayoutFrame = <function> defined @SharedXML/LayoutFrame.lua:36
 OnShow = <function> defined @SharedXML/LayoutFrame.lua:32
 Background = Frame {
 }
 AddLayoutChildren = <function> defined @SharedXML/LayoutFrame.lua:48
 IgnoreLayoutIndex = <function> defined @SharedXML/LayoutFrame.lua:329
}
flyoutID = 103
parent = MultiBarBottomRightButton2 {
 0 = <userdata>
 OnEnter = <function> defined @FrameXML/ActionButton.lua:1200
 FlyoutArrowContainer = Frame {
 }
 NewActionTexture = Texture {
 }
 RightDivider = Frame {
 }
 DoModeChange = <function> defined @FrameXML/QuickKeybind.lua:95
 UpdateButtonArt = <function> defined @FrameXML/ActionButton.lua:1245
 QuickKeybindButtonOnLeave = <function> defined @FrameXML/QuickKeybind.lua:33
 UpdateAction = <function> defined @FrameXML/ActionButton.lua:357
 OnReceiveDrag = <function> defined @FrameXML/ActionButton.lua:1194
 icon = MultiBarBottomRightButton2Icon {
 }
 SlotArt = Texture {
 }
 AutoCastable = Texture {
 }
 UpdateTooltip = <function> defined @FrameXML/ActionButton.lua:914
 UpdateState = <function> defined @FrameXML/ActionButton.lua:494
 UpdatePressAndHoldAction = <function> defined @FrameXML/ActionButton.lua:340
 HotKey = MultiBarBottomRightButton2HotKey {
 }
 HighlightTexture = Texture {
 }
 UpdateOverlayGlow = <function> defined @FrameXML/ActionButton.lua:707
 GetPagedID = <function> defined @FrameXML/ActionButton.lua:1005
 Update = <function> defined @FrameXML/ActionButton.lua:373
 ClearProfessionQuality = <function> defined @FrameXML/ActionButton.lua:540
 IconMask = MaskTexture {
 }
 SetPoint = <function> defined =[C]:-1
 SpellHighlightAnim = AnimationGroup {
 }
 OnLoad = <function> defined @FrameXML/ActionButton.lua:279
 PushedTexture = Texture {
 }
 SetTooltip = <function> defined @FrameXML/ActionButton.lua:914
 Count = MultiBarBottomRightButton2Count {
 }
 UpdateUsable = <function> defined =[C]:-1
 FlyoutBorderShadow = MultiBarBottomRightButton2FlyoutBorderShadow {
 }
 GetShowGrid = <function> defined @FrameXML/ActionButton.lua:1227
 SetButtonStateBase = <function> defined =[C]:-1
 UpdateHotkeys = <function> defined @FrameXML/ActionButton.lua:303
 rangeTimer = -1
 Border = MultiBarBottomRightButton2Border {
 }
 Flash = MultiBarBottomRightButton2Flash {
 }
 index = 2
 gwY = 0
 gwBackdrop = Frame {
 }
 flashtime = 0
 CalculateAction = <function> defined @FrameXML/SecureTemplates.lua:609
 OnUpdate = <function> defined @FrameXML/ActionButton.lua:933
 HasAction = <function> defined @FrameXML/ActionButton.lua:490
 QuickKeybindButtonSetTooltip = <function> defined @FrameXML/QuickKeybind.lua:52
 showMacroName = true
 commandName = "MULTIACTIONBAR2BUTTON2"
 SetButtonStateOverride = <function> defined @FrameXML/ActionButton.lua:1140
 QuickKeybindHighlightTexture = Texture {
 }
 OnDragStart = <function> defined @FrameXML/ActionButton.lua:1182
 changedColor = false
 feedback_action = 50
 QuickKeybindButtonOnEnter = <function> defined @In

**Comment by HeercoGrond** [comment]
This Error also occurs on the Dragonflying tab - It's something specific with the 'SpellFlyOutTab'. that isn't working on the latest version of GW2 UI

**Comment by Nils89** [comment]
This is a blizzard error, flout buttons only works on the main action bar, till they fix it
