### ISSUE TITLE
Low resolution for event(?) texts

### ISSUE THREAD

**Issue by Snuffsis** [Mortalknight/GW2_UI#190]
I just installed the GW2 UI for WotLK classic and it works great, except for the issue that during certain events, the game shows a message on the screen, but it appears to be very low resolution, as you can see in the image below.
![image](https://user-images.githubusercontent.com/8822958/213898799-c3de0ed5-47d9-4ae6-a7f7-e31544a3063c.png)

I have Pixel Perfect mode on and scaling disabled in blizzard settings. I tried checking other addons I have that might interfere, but nothing from what I could see.

**Comment by Snuffsis** [comment]
Found the cause of it. Seems to be the GW2 font option.

Disabling "Fonts" in the Modules section made it go away, but then of course you would also lose the GW2 fonts for everything else as well.

**Comment by Nils89** [comment]
try 1.8.7
