### ISSUE TITLE
WoW Classic Era: Questie preventing tracker updates

### ISSUE THREAD

**Issue by ImaanBontle** [Mortalknight/GW2_UI#191]
Hi, no idea if this has been reported before, but whenever Questie is activated and you enable the zone sorting setting (requires Questie), the GW2 quest tracker stops updating entirely and objectives remain static. This affects all types of updates (loot, turn-ins, accepting etc) and the only solution seems to be to use default or level sorting.

The following error also occurs when looting quest corpses (although may be unrelated):

```
Version: 2.0.6-Era Classic Era Date: 01/27/23 13:21:31 Locale: enUS Build 1.14.3 46575
[13:20:57] [ERROR]: "GW2_UI\objectives/objectives.lua:903: attempt to index field 'utils' (a nil value)"
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "GW2_UI\objectives/objectives.lua"]:903: in function <GW2_UI\objectives/objectives.lua:898>
[string "=[C]"]: in function `sort'
[string "GW2_UI\objectives/objectives.lua"]:898: in function <GW2_UI\objectives/objectives.lua:864>
[string "GW2_UI\objectives/objectives.lua"]:973: in function <GW2_UI\objectives/objectives.lua:972>
```

### Addons:

- GW2 UI v2.0.6-Era
- Questie v7.4.10.

**Comment by Nils89** [comment]
fixed in 2.0.7-Era
