### ISSUE TITLE
Lua Error when using a skill like summon pet or dragonriding

### ISSUE THREAD

**Issue by Consequenz** [Mortalknight/GW2_UI#192]
Message: Interface/FrameXML/SpellFlyout.lua:240: attempt to call method 'GetSpellFlyoutDirection' (a nil value)
Count: 1
Stack: Interface/FrameXML/SpellFlyout.lua:240: attempt to call method 'GetSpellFlyoutDirection' (a nil value)
[string "=[C]"]: in function `GetSpellFlyoutDirection'
[string "@Interface/FrameXML/SpellFlyout.lua"]:240: in function `Toggle'
[string "@Interface/FrameXML/SecureTemplates.lua"]:361: in function `handler'
[string "@Interface/FrameXML/SecureTemplates.lua"]:690: in function <Interface/FrameXML/SecureTemplates.lua:672>
[string "@Interface/FrameXML/SecureTemplates.lua"]:704: in function <Interface/FrameXML/SecureTemplates.lua:697>
[string "@Interface/FrameXML/SecureTemplates.lua"]:746: in function `SecureActionButton_OnClick'
[string "@Interface/FrameXML/ActionButton.lua"]:1155: in function <Interface/FrameXML/ActionButton.lua:1125>
[string "=[C]"]: ?

Locals:

**Comment by Nils89** [comment]
This is a blizzard bug, fly out buttons only works on the main action bar atm
