### ISSUE TITLE
issue with opening map causing errors when using GW2 UI and Questie addon

### ISSUE THREAD

**Issue by MyTechnoHunter** [Mortalknight/GW2_UI#195]
User came to Questie discord to report an error showing up after they used CF client to update all addons they had installed
using latest available GW2 UI and latest release of Questie they get the following showing up..

```
Message: ...erface/AddOns/Questie/Modules/QuestieCoordinates.lua:86: attempt to index a nil value
Time: Tue May 23 09:10:33 2023
Count: 8
Stack: ...erface/AddOns/Questie/Modules/QuestieCoordinates.lua:86: attempt to index a nil value
[string "=[C]"]: ?
[string "@Interface/AddOns/Questie/Modules/QuestieCoordinates.lua"]:86: in function `WriteCoords'
[string "@Interface/AddOns/Questie/Modules/QuestieCoordinates.lua"]:113: in function <...erface/AddOns/Questie/Modules/QuestieCoordinates.lua:106>

Locals:
```
looking into it the only way that happens is if the following fails..
line 86 = GetMapTitleText():SetText(worldmapCoordsText)
the function in question is
```lua
local function GetMapTitleText()

    local regions = {WorldMapFrame.BorderFrame:GetRegions()}
    for i = 1, #regions do
        if (regions[i].SetText) then
            return regions[i]
        end
    end
end
```

does the GW2 UI addon perchance rename/remove/change the mapframe?

thanks for looking into this

**Comment by Nils89** [comment]
You can disable the Questie map coordinates to fix this
