### ISSUE TITLE
Feature Request: Reset Window Position

### ISSUE THREAD

**Issue by Xogue** [Mortalknight/GW2_UI#196]
I am not even sure how i did it, but one of the windows (the character window specifically) got outside of the display boundaries. I could not get it back. I tried to resize the UI through WoW, disabling and re-enabling the addon, restarting it. In the end, I had to reset to default settings which brought it back, but it was a pain to have to set everything back up again.

More of a suggestion I guess. maybe a "reset window positions" button somewhere in the settings?

Edit: This is for Wow Hardcore, not sure about other versions

**Comment by Nils89** [comment]
there is an option for that /gw2 reset windows
