### ISSUE TITLE
[Feature Request] Pet Frame losing hp background fill like target

### ISSUE THREAD

**Issue by AngelosNaoumis** [Mortalknight/GW2_UI#206]
It would be good to have same animation/texture in pet frame as player/target when losing HP and trying to regen it (as currently is plain)
e.g.
![image](https://github.com/Mortalknight/GW2_UI/assets/25444260/75e1c1bc-e6ba-4681-b2bd-115be8b8db5d)

**Comment by Nils89** [comment]
fixed
