### ISSUE TITLE
Main Menu Frame

### ISSUE THREAD

**Issue by reap3rx** [Mortalknight/GW2_UI#224]
Version: GW2_UI 7.0.2 Date: 07/27/24 14:38:14 Locale: enUS Build 11.0.0 55824
[14:37:47] [ERROR]: "...face/AddOns/GW2_UI/immersive/skins/mainMenuFrame.lua:57: attempt to index a nil value"
[string "GW2_UI/immersive/skins/mainMenuFrame.lua"]:57: in function <...face/AddOns/GW2_UI/immersive/skins/mainMenuFrame.lua:56>
[string "=[C]"]: in function `xpcall'
[string "Blizzard_SharedXMLBase/FunctionUtil.lua"]:4: in function <...rface/AddOns/Blizzard_SharedXMLBase/FunctionUtil.lua:1>
[string "=[C]"]: in function `pcall'
[string "ConsolePort_Cursor/Controller/Scripts.lua"]:17: in function `ExecuteScript'
[string "ConsolePort_Cursor/View/Cursor.lua"]:502: in function `OnEnterNode'
[string "ConsolePort_Cursor/View/Cursor.lua"]:538: in function `Select'
[string "ConsolePort_Cursor/View/Cursor.lua"]:533: in function <ConsolePort_Cursor/View/Cursor.lua:528>
[string "=(tail call)"]: ?
[string "=(tail call)"]: ?
[string "=(tail call)"]: ?
[string "=(tail call)"]: ?
[string "=(tail call)"]: ?
[string "ConsolePort_Cursor/Controller/Stack.lua"]:173: in function <...rface/AddOns/ConsolePort_Cursor/Controller/Stack.lua:171>
[14:37:47] [ERROR]: "...face/AddOns/GW2_UI/immersive/skins/mainMenuFrame.lua:60: attempt to index a nil value"
[string "GW2_UI/immersive/skins/mainMenuFrame.lua"]:60: in function <...face/AddOns/GW2_UI/immersive/skins/mainMenuFrame.lua:59>
[string "=[C]"]: in function `xpcall'
[string "Blizzard_SharedXMLBase/FunctionUtil.lua"]:4: in function <...rface/AddOns/Blizzard_SharedXMLBase/FunctionUtil.lua:1>
[string "=[C]"]: in function `pcall'
[string "ConsolePort_Cursor/Controller/Scripts.lua"]:17: in function `ExecuteScript'
[string "ConsolePort_Cursor/View/Cursor.lua"]:496: in function `OnLeaveNode'
[string "ConsolePort_Cursor/View/Cursor.lua"]:165: in function `Refresh'
[string "ConsolePort_Cursor/View/Cursor.lua"]:223: in function <ConsolePort_Cursor/View/Cursor.lua:219>

I haven't noticed any issues, save that my action bars keep resetting to nothing being saved in it when I log in (could be a ConsolePort issue though) but this error popped up in chat so I though I'd post it.

**Comment by Nils89** [comment]
Can you try it with only gw2 enabled?
