### ISSUE TITLE
v4.2.1 Minimap Button Show/Hide Issues

### ISSUE THREAD

**Issue by InkDragon** [Mortalknight/GW2_UI#31]
The new show hide button for the minimap is currently awkwardly placed(directly over the garrison/order hall report button). Easily fixable by either making it moveable or moving it directly above the calendar button

An additional issue is that it it also hides [Handynotes](https://www.curseforge.com/wow/addons/handynotes) minimap markers, after showing then hiding the buttons.

**Comment by Nils89** [comment]
For the Minimap Butto:
Set the minimap Scale in Settings new. This will fix the overlapping.

**Comment by Nils89** [comment]
The second thing is fixed and will upload in the next update.
