### ISSUE TITLE
Frequent quest tracker updates cause considerable FPS drop

### ISSUE THREAD

**Issue by adsamcik** [Mortalknight/GW2_UI#34]
QUEST_LOG_UPDATE event is called really often and triggers quest tracker updating. Consider using UNIT_QUEST_LOG_CHANGED, it seems to be much more fps friendly. Also are all the quest events needed?

"However, if you are ONLY interested in tracking QUEST-related information (accepting quests, abandoning quests, achieving quest progress, and completing quests), there's a better event: UNIT_QUEST_LOG_CHANGED."

**Comment by Kyoji** [comment]
@adsamcik I did a blind find/replace updating QUEST_LOG_UPDATE to UNIT_QUEST_LOG_CHANGED which seemed to fix the FPS stuttering issues, however I think it broke the compass. Personally I'm ok with the trade off until an actual fix is developed. 

If you'd like you can use my fork here: https://github.com/Kyoji/GW2_UI

**Comment by adsamcik** [comment]
I updated it myself too and based on what I did I posted this issue. My compass worked fine, but there were some issue when it didn't update where it should. These issues weren't apparent immediately but manifested after tens of completed quests. 

The main problem of the drawing code is that it blindly just redraws on event without checking for changes. 

This addon while nice has too many bugs to use normally so I just replaced it when I hit 110.

**Comment by Kyoji** [comment]
What other bugs have you noticed? Everything except the quest tracker seems to work pretty well.

**Comment by adsamcik** [comment]
https://github.com/Mortalknight/GW2_UI/issues/33 stands out, it was really annoying, never bothered to fix it though. There were some UI issues with vehicles or something? Can't recall exactly. There were few more issues but I don't remember which, just that there were.

**Comment by nezroy** [comment]
This is resolved as of the 4.2.4 release. Please open a new issue if you continue to see issues. Thanks!
