### ISSUE TITLE
Plugin development support

### ISSUE THREAD

**Issue by inzenir** [Mortalknight/GW2_UI#35]
Hi,

I've started using this wonderful GUI addon last night and missed a few features. Thought I'd just write a plugin, but I was either too tired to remember how to actually do it or just too stupid to manage, so I ended up adding some 20 lines to the UI and it works just fine. Is there a good way of making a plugin for this addon?

**Comment by nezroy** [comment]
There is not, and that kind of integration is unfortunately low on our priority list compared to other things we're trying to get done. If you tell us what you added though we might be able to just add it baseline to the UI as a new option :)

**Comment by inzenir** [comment]
I added empty bag slot counter on the bag icon on the top and started adding an option to have currencies  in character tab instead of bags (as some use use other bad addons). I could refractor that and add fork out and make pull requests.

**Comment by nezroy** [comment]
Currencies in the character tab is actually on our list of things to add already so that should be coming soon regardless. Bag slot counter on the bag icon seems like a good idea so if you want to create a PR for that I'm pretty sure we'd merge that.
