### ISSUE TITLE
Character panel toggle is not working

### ISSUE THREAD

**Issue by bubblefarts** [Mortalknight/GW2_UI#72]
Based on the sound that it makes when I press "C" (the key assigned to the character panel) the panel wont show up, in fact the sound of the panel closing is the only thing I can hear when using the keybind, but if  I click the menu button for the character panel then it shows the pane, I can close the panel with the keybind but the keybind wont open it.

**Comment by nezroy** [comment]
This has been fixed in the latest 8x branch. I'll try to tag a new alpha build for this right away.
