### ISSUE TITLE
Suggestion: Add bonus lvls to M+ timer.

### ISSUE THREAD

**Issue by mike0891** [Mortalknight/GW2_UI#83]
I would love if the timer for M+ showed when you key goes up +2 or 3.

- Beating the timer with less than 20% remaining, results in a +1 upgrade, e.g. from 3 to 4

- Beating the timer with more than 20% but less than 40% remaining, results in a +2 upgrade, e.g. from 3 to 5

- Beating the timer with more than 40% of the allotted time remaining, results in a +3 upgrade, e.g. from 3 to 6

This could be just a gold line at 60% then 80% to show when the timer hits these points.

**Comment by Nils89** [comment]
Everything incl. death counter is in the next update
