### ISSUE TITLE
FPS drop

### ISSUE THREAD

**Issue by doomonline** [Mortalknight/GW2_UI#86]
Exits a currently playing in-game cinematic and select an enemy or a player, fps will drop to 20-30.

**Comment by critaL** [comment]
I can confirm this. The way i "solve" it is by reloading the UI

**Comment by doomonline** [comment]
Fix it，please

**Comment by doomonline** [comment]
Why not fix this bug? I really like this addon, but this problem greatly affects the experience

**Comment by Nils89** [comment]
Disable the buff module. 
Should be fixed in the next version

**Comment by doomonline** [comment]
Thank you, really good addon

Nils89 <notifications@github.com> 于2020年4月7日周二 上午12:38写道：

**Comment by Apofixc** [comment]
> Disable the buff module.
> Should be fixed in the next version

this problem was solved by disable tracker module

**Comment by Nils89** [comment]
fixed with 5.4.8
