### ISSUE TITLE
Classic: "You must unequip that item in order to upgrade it" when trying to apply poison etc.

### ISSUE THREAD

**Issue by rvplauborg** [Mortalknight/GW2_UI#91]
Hi,

It seems like the "You must unequip that item in order to upgrade it." error message, which was meant for specific things, also unfortunately applies when just attempting to apply poison in WoW Classic as a rogue. The workaround is to unequip weapons and apply poison and reequip, which is very tiresome.

**Comment by Nils89** [comment]
That’s correct, a fix is not planed at the moment
