### ISSUE TITLE
Classic: "Wrong object type for function" when changing zones

### ISSUE THREAD

**Issue by chief-tyrol** [Mortalknight/GW2_UI#93]
Haven't had time to dig into it yet, but for the last few months I've been getting the following error whenever I change zones (e.g. enter/leave a dungeon or raid, or use a mage portal):

[This is the line in question](https://github.com/Mortalknight/GW2_UI/blob/2725886115af577958a16d5d6151506d1c69746c/objectives/map.lua#L346)

```
Date: 2020-05-12 10:04:46
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\GW2_UI\objectives/map.lua line 346:
   Wrong object type for function
Debug:
   [C]: SetParent()
   GW2_UI\objectives/map.lua:346:
      GW2_UI\objectives/map.lua:344
   GW2_UI\objectives/map.lua:390:
      GW2_UI\objectives/map.lua:388
Locals:
(*temporary) = <table> {
}
(*temporary) = Minimap {
 timer = 0
 SetScale = <function> defined =[C]:-1
 0 = <userdata>
}
(*temporary) = nil

AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  AtlasLootClassic, vv1.5.1
  AtlasLootClassicData, vv1.5.1
  AtlasLootClassicDungeonsAndRaids, vv1.5.1
  AucAdvanced, v8.2.6430 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucScanData, v8.2.6365 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6399 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  AuctionDB, vv1.02.01
  BeanCounter, v8.2.6434 (SwimmingSeadragon)
  BetterVendorPrice, vv1.13.04
  ClassicCodex, v1.2.3
  DBMCore, v1.13.44
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  Details, v
  DetailsStreamer, v
  DetailsTinyThreat, v
  DruidBarClassic, v0.7.7
  Enchantrix, v8.2.6428 (SwimmingSeadragon)
  EnchantrixBarker, v8.2.6469 (SwimmingSeadragon)
  GeartoGearPlanner, vv1.3.7
  GW2UI, v
  Informant, v8.2.6374 (SwimmingSeadragon)
  ItemRack, v
  LibHealComm40, v
  Pawn, v2.3.25
  SlideBar, v8.2.6375 (SwimmingSeadragon)
  Stubby, v8.2.6376 (SwimmingSeadragon)
  ThreatClassic2, v2.19
  WeaponSwingTimer, v4.1.0
  BlizRuntimeLib_enUS v1.13.4.11304 <none>
  (ck=4d9)
```

Afterwards, the `AHDB` "scan" button is no longer with the rest of the map buttons in the expander, but is instead stuck on the side of the map, and clicking the three dots no longer expands/hides the map button menu (it stays in whatever state it was in prior to the zone change).

Reloading the UI fixes the issue, until the next time I change zones (it happens 100% of the time).

I _think_ the issue started with `v1.7.2`, but I'm not sure.

Here's an example of what it looks like if the expander was closed prior to changing zones:
![World Of Warcraft - Classic Screenshot 2020 05 12 - 10 05 48 75 (2)](https://user-images.githubusercontent.com/3124733/81730348-ff51c700-9452-11ea-8e0e-c549f46b5b50.png)

And here's an example of what it looks like if it were open prior to changing zones:
![World Of Warcraft - Classic Screenshot 2020 05 12 - 13 11 51 46 (2)](https://user-images.githubusercontent.com/3124733/81730394-1395c400-9453-11ea-9fe7-a731c5f56883.png)

This is what it looks like normally, when closed:
![World Of Warcraft - Classic Screenshot 2020 05 12 - 13 12 07 17 (2)](https://user-images.githubusercontent.com/3124733/81730444-29a38480-9453-11ea-8a4e-06ffbaf6d670.png)

And what it looks like normally, when open:
![World Of Warcraft - Classic Screenshot 2020 05 12 - 13 12 10 91 (2)](https://user-images.githubusercontent.com/3124733/81730469-33c58300-9453-11ea-8e0d-fa33b21b4324.png)

**Comment by Nils89** [comment]
Could you try it with AHDB addon disabled?

**Comment by chief-tyrol** [comment]
With `AHDB` disabled I don't get the error, and the expand/shrink button continues to work after changing zones
